version: '3.7'

networks:
  owms:

volumes:
  database: {}
  prometheus_data: {}
  grafana_data: {}

services:
  tracing:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
    networks:
      - owms

  rabbitmq:
    build: ./monitoring/rabbitmq
    ports:
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - owms

  srv:
#    build: ../../spring-labs/org.openwms.services
    image: "interface21/openwms-services:latest"
    ports:
      - "8762:8761"
    networks:
      - owms

  cfg:
#    build: ../../spring-labs/org.openwms.configuration
    image: "interface21/openwms-configuration:latest"
    ports:
    - "8099:8099"
    environment:
      spring.cloud.config.server.git.uri: https://github.com/spring-labs/org.openwms.zile
      spring.cloud.config.server.git.searchPaths: conf
      spring.cloud.config.server.git.clone-on-start: "true"
      spring.rabbitmq.host: rabbitmq
      spring.zipkin.base-url: http://tracing:9411/
      owms.eureka.url: http://user:sa@srv:8761
      owms.srv.hostname: cfg
    networks:
      - owms

  tcp-palettconv:
#    build: ../../openwms/org.openwms.common.comm
    image: "openwms/org.openwms.common.comm:latest"
    restart: on-failure:10
    ports:
      - "30001:30001"
      - "30002:30002"
    environment:
      spring.application.name: tcpip-palettconv
      spring.profiles.active: "ASYNCHRONOUS,DISTRIBUTED,ZILE"
      spring.zipkin.base-url: http://tracing:9411/
      spring.rabbitmq.host: rabbitmq
      owms.eureka.url: http://user:sa@srv:8761
      owms.srv.hostname: tcpip-palettconv
    networks:
      - owms

  common-service:
#    build: ../../openwms/org.openwms.common.service
    image: "openwms/org.openwms.common.service:latest"
    restart: on-failure:10
    environment:
      spring.profiles.active: "ASYNCHRONOUS,DISTRIBUTED,ZILE"
      spring.zipkin.base-url: http://tracing:9411/
      spring.rabbitmq.host: rabbitmq
      owms.eureka.url: http://user:sa@srv:8761
      owms.srv.hostname: common-service
    networks:
      - owms

  tms-service:
#    build: ../../openwms/org.openwms.tms.transportation
    image: "openwms/org.openwms.tms.transportation:latest"
    restart: on-failure:10
    environment:
      spring.profiles.active: "ASYNCHRONOUS,DISTRIBUTED,ZILE"
      spring.zipkin.base-url: http://tracing:9411/
      spring.rabbitmq.host: rabbitmq
      owms.eureka.url: http://user:sa@srv:8761
      owms.srv.hostname: tms-service
    networks:
      - owms

  routing-service:
#    build: ../../openwms/org.openwms.tms.routing
    image: "openwms/org.openwms.tms.routing:latest"
    restart: on-failure:10
    environment:
      spring.profiles.active: "ASYNCHRONOUS,DISTRIBUTED,ZILE"
      spring.zipkin.base-url: http://tracing:9411/
      spring.rabbitmq.host: rabbitmq
      owms.eureka.url: http://user:sa@srv:8761
    networks:
      - owms

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus/
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    networks:
      - owms
    restart: always

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./monitoring/alertmanager/:/etc/alertmanager/
    networks:
      - owms
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - owms
    restart: always
    deploy:
      mode: global

  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./monitoring/grafana/config.monitoring
    networks:
      - owms
    restart: always
