version: '3'

networks:
  owms:
    driver: bridge

services:

  tracing:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
    networks:
      - owms

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - owms

  srv:
#    build: ../../interface21/org.openwms.services
    image: "interface21/openwms-services:1.1.0"
    ports:
      - "8761:8761"
    networks:
      - owms

      
  cfg:
#    build: ../../interface21/org.openwms.configuration
    image: "interface21/openwms-configuration:1.1.0"
    hostname: cfg
    ports:
      - "8099:8099"
    environment:
      spring.cloud.config.server.git.uri: https://github.com/spring-labs/org.openwms.zile
      spring.cloud.config.server.git.searchPaths: conf
      spring.cloud.config.server.git.clone-on-start: "true"
      owms.eureka.url: http://user:sa@srv:8761
      owms.srv.hostname: cfg
    networks:
      - owms

  common-service:
#    build: ../../openwms/org.openwms.common.service
    image: "openwms/org.openwms.common.service:1.5.0"
    restart: on-failure:10
    hostname: common-service
    ports:
      - "8120:8120"
    environment:
      spring.cloud.config.fail-fast: "true"
      spring.profiles.active: "ASYNCHRONOUS,DEMO"
      spring.zipkin.base-url: http://tracing:9411/
      spring.rabbitmq.host: rabbitmq
      owms.eureka.url: http://user:sa@srv:8761
      owms.srv.hostname: common-service
    networks:
      - owms
      
  tms-transportation:
#    build: ../../openwms/org.openwms.tms.transportation
    image: "openwms/org.openwms.tms.transportation:1.3.0"
    restart: on-failure:10
    hostname: tms-transportation
    ports:
      - "8131:8131"
    environment:
      spring.profiles.active: "ASYNCHRONOUS,DEMO"
      spring.zipkin.base-url: http://tracing:9411/
      spring.rabbitmq.host: rabbitmq
      owms.eureka.url: http://user:sa@srv:8761
      owms.srv.hostname: tms-transportation
    networks:
      - owms
      
  routing-service:
#    build: ../../openwms/org.openwms.tms.routing
    image: "openwms/org.openwms.tms.routing:1.2.0"
    restart: on-failure:10
    hostname: routing-service
    ports:
      - "8130:8130"
    environment:
      spring.profiles.active: "ASYNCHRONOUS,DEMO"
      spring.zipkin.base-url: http://tracing:9411/
      spring.rabbitmq.host: rabbitmq
      owms.eureka.url: http://user:sa@srv:8761
    networks:
      - owms

  tcp-palettconv:
    #    build: ../../openwms/org.openwms.common.comm
    image: "openwms/org.openwms.common.comm:latest"
    restart: on-failure:10
    hostname: tcp-palettconv
    ports:
      - "30001:30001"
      - "30002:30002"
    environment:
      spring.application.name: tcpip-palettconv
      spring.profiles.active: "ASYNCHRONOUS,DISTRIBUTED"
      spring.zipkin.base-url: http://tracing:9411/
      spring.rabbitmq.host: rabbitmq
      owms.eureka.url: http://user:sa@srv:8761
    networks:
      - owms
