version: '3.7'

networks:
  owms:

services:

  ####################################################
  ## Zipkin UI for Microservice Monitoring (Port 9411)
  ####################################################
  tracing:
    image: openzipkin/zipkin:2.21.5
    ports:
      - "9411:9411"
    networks:
      - owms

  ####################################################
  ## RabbitMQ Message Broker (UI at Port 15673)
  ####################################################
  rabbitmq:
    build: ./monitoring/rabbitmq
    ports:
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - owms

  ####################################################
  ## OpenWMS Eureka Service Registry (UI at Port 8761)
  ####################################################
  srv:
    image: "interface21/openwms-services:latest"
    environment:
      spring.zipkin.base-url: http://tracing:9411/
    ports:
      - "8762:8761"
    networks:
      - owms

  ####################################################
  ## OpenWMS Central Configuration Server
  ####################################################
  cfg:
    image: "interface21/openwms-configuration:latest"
    ports:
    - "8099:8099"
    environment:
      spring.cloud.config.server.git.uri: https://github.com/spring-labs/org.openwms.zile
      spring.cloud.config.server.git.searchPaths: conf
      spring.cloud.config.server.git.clone-on-start: "true"
      spring.rabbitmq.host: rabbitmq
      spring.zipkin.base-url: http://tracing:9411/
      owms.eureka.url: http://user:sa@srv:8761
      owms.srv.hostname: cfg
    networks:
      - owms

  ####################################################
  ## OpenWMS TCP/IP Driver for palette conveyor
  ####################################################
  tcp-palettconv:
    image: "openwms/org.openwms.common.comm:latest"
    restart: on-failure:10
    ports:
      - "30001:30001"
      - "30002:30002"
    environment:
      spring.application.name: tcpip-palettconv
      spring.profiles.active: "ASYNCHRONOUS,DISTRIBUTED,ZILE"
      spring.zipkin.base-url: http://tracing:9411/
      spring.rabbitmq.host: rabbitmq
      owms.eureka.url: http://user:sa@srv:8761
      owms.srv.hostname: tcpip-palettconv
    networks:
      - owms

  ####################################################
  ## OpenWMS COMMON Services
  ####################################################
  common-service:
    image: "openwms/org.openwms.common.service:latest"
    restart: on-failure:10
    environment:
      spring.profiles.active: "ASYNCHRONOUS,DISTRIBUTED,ZILE"
      spring.zipkin.base-url: http://tracing:9411/
      spring.rabbitmq.host: rabbitmq
      owms.eureka.url: http://user:sa@srv:8761
      owms.srv.hostname: common-service
    networks:
      - owms

  ####################################################
  ## OpenWMS Transportation Service
  ####################################################
  tms-service:
    image: "openwms/org.openwms.tms.transportation:latest"
    restart: on-failure:10
    environment:
      spring.profiles.active: "ASYNCHRONOUS,DISTRIBUTED,ZILE"
      spring.zipkin.base-url: http://tracing:9411/
      spring.rabbitmq.host: rabbitmq
      owms.eureka.url: http://user:sa@srv:8761
      owms.srv.hostname: tms-service
    networks:
      - owms

  ####################################################
  ## OpenWMS Routing Services
  ####################################################
  routing-service:
    image: "openwms/org.openwms.tms.routing:latest"
    restart: on-failure:10
    environment:
      spring.profiles.active: "ASYNCHRONOUS,DISTRIBUTED,ZILE"
      spring.zipkin.base-url: http://tracing:9411/
      spring.rabbitmq.host: rabbitmq
      owms.eureka.url: http://user:sa@srv:8761
    networks:
      - owms
