version: '3.7'

networks:
  owms:

services:
  tracing:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
    networks:
      - owms

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - owms

  srv:
#    build: ../../interface21/org.openwms.services
    image: "interface21/openwms-services:latest"
    ports:
      - "8762:8761"
    networks:
      - owms

      
  cfg:
#    build: ../../interface21/org.openwms.configuration
    image: "interface21/openwms-configuration:latest"
    environment:
      spring.cloud.config.server.git.uri: https://github.com/spring-labs/org.openwms.zile
      spring.cloud.config.server.git.searchPaths: conf
      spring.cloud.config.server.git.clone-on-start: "true"
      owms.eureka.url: http://user:sa@srv:8761
      owms.srv.hostname: cfg
    networks:
      - owms

  tcp-palettconv:
    #    build: ../../openwms/org.openwms.common.comm
    image: "openwms/org.openwms.common.comm:latest"
    restart: on-failure:10
    ports:
      - "30001:30001"
      - "30002:30002"
    environment:
      spring.application.name: tcpip-palettconv
      spring.profiles.active: "ASYNCHRONOUS,DISTRIBUTED"
      spring.zipkin.base-url: http://tracing:9411/
      spring.rabbitmq.host: rabbitmq
      owms.eureka.url: http://user:sa@srv:8761
    networks:
      - owms

  common-service:
    #    build: ../../openwms/org.openwms.common.service
    image: "openwms/org.openwms.common.service:latest"
    restart: on-failure:10
    environment:
      spring.profiles.active: "ASYNCHRONOUS,ZILE"
      spring.zipkin.base-url: http://tracing:9411/
      spring.rabbitmq.host: rabbitmq
      owms.eureka.url: http://user:sa@srv:8761
      owms.srv.hostname: common-service
    networks:
      - owms

  tms-service:
    #    build: ../../openwms/org.openwms.tms.transportation
    image: "openwms/org.openwms.tms.transportation:latest"
    restart: on-failure:10
    environment:
      spring.profiles.active: "ASYNCHRONOUS,ZILE"
      spring.zipkin.base-url: http://tracing:9411/
      spring.rabbitmq.host: rabbitmq
      owms.eureka.url: http://user:sa@srv:8761
      owms.srv.hostname: tms-service
    networks:
      - owms

  routing-service:
    #    build: ../../openwms/org.openwms.tms.routing
    image: "openwms/org.openwms.tms.routing:latest"
    restart: on-failure:10
    environment:
      spring.profiles.active: "ASYNCHRONOUS,ZILE"
      spring.zipkin.base-url: http://tracing:9411/
      spring.rabbitmq.host: rabbitmq
      owms.eureka.url: http://user:sa@srv:8761
    networks:
      - owms
