security:
  user:
    password: sa
# In production environment the config server uses a keystore or vault to protect password.
#    password: '{cipher}AQCBEJQaBHFtllY7nnOyW14gwaJbwqzV9CAf9YFPQf310wRonMc45J4cWb3hoJIfcTaMTLa+DDOqCFSDdFiI8PoDUoj44sUV4GLBnlBxtaJp0OF2Sv7H3XLFdOovJksRPYoJW8m5e9GTzwTyQt3IRJ+NuUJRorOQ7Cb8gtKhgSUHMR710lcdGSIanj512Ewi7xcUYUzHLfU0L+wdLX3k3dkJgtMxaJZMSGfREXz6V3ndeCk8mAnFy0tt/G6ftxfzLKQgdd3S7MkfoZBXHL1DdxS+vW+/S0pDrqs8o9WNX9O1VaYokhwymVFRGkJv5ASmerLzmh3YWkzbfqkg6lwxL/npauGcc+EOs9v/bN5e6QcPePfZMMlVVNjBXbP3VoAKLic='

---
spring:
  profiles: "!ASYNCHRONOUS"

owms:
  partners:
    sps01: SPS01
    sps02: SPS02
    sps03: SPS03
    sps04: SPS04
    sps05: SPS05

---
spring:
  profiles: ASYNCHRONOUS

owms:
  partners:
    sps01: osip.res.1
    sps02: osip.res.2
    sps03: osip.res.3
    sps04: osip.res.4
    sps05: osip.res.5

---
spring:
  profiles: ZILE
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create # Must be create in order to load test data
    properties:
      hibernate:
        hbm2ddl:
          import_files: import-DEMO.sql
